### ISSUE TITLE
Version 2.3.1 on flathub

### ISSUE THREAD

**Issue by Marzal** [Nitrokey/nitrokey-app2#265]
Hi, new user of the Nitrokey3, great product!
I'm getting up to speed with all this new world and I have found that the flatpak version is outdated. Are you planing in pushing the new version?

https://github.com/flathub/com.nitrokey.nitrokey-app2

Thanks for your work.

**Comment by robin-nitrokey** [comment]
Indeed the flatpak package is not up to date.  We are working on releasing the new version there but it is not quite ready yet.

The reason is that one of our dependencies currently does not build in the flatpak builder environment.  We are waiting for upstream to merge and release our fix (https://github.com/pyocd/cmsis-pack-manager/pull/230).  At the same time, we are implementing a workaround for the issue that entirely removes the dependency.  This will take some more time but hopefully we will be able to update the package soon.

**Comment by daringer** [comment]
version will - due to the aforementioned issue - not be available on flathub - recent changes made this possible again. Closing this issue, expect v2.3.2 to be available through flatpak again...
