### ISSUE TITLE
PyPI not up-to-date

### ISSUE THREAD

**Issue by brevilo** [Nitrokey/nitrokey-app2#289]
Please add PyPI to your release process. It still [lacks](https://pypi.org/project/nitrokeyapp/#history) the 2.3.2 release.

Thank you

**Comment by mmerklinger** [comment]
I haven't confirmed it through testing, but I have an assumption. We usually create a release as a _prerelease_ and then change it later to _release_. The workflow for PyPI is only triggered on the release event. Changing it later on probably doesn't trigger the other event.

The thought of not triggering prereleases to PyPI was to not have a testing release pushed to users. I see two options:

1. See if we can trigger the workflow on such a change.
2. Change our release process, which is mostly like that due to manual signing of the Windows artifacts. Though we also use it to make some final release tests sometimes.

**Comment by robin-nitrokey** [comment]
I also had that idea, but looking at the old workflow runs, it seems like the previous releases were first tagged as prereleases too.  Also, the [documentation](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#release) refers to [this site](https://docs.github.com/en/webhooks/webhook-events-and-payloads#release) that says:

> Action type: released
> A release was published, or a pre-release was changed to a release.

**Comment by mmerklinger** [comment]
You are right. I also checked when we last time changed the release event behavior and it was long time before the last published release on PyPI. I'm not sure right now what is going on, but I can conduct some tests in the coming days.

**Comment by mmerklinger** [comment]
So, regarding my assumption from the last comment I was right. Means, we just need to adapt our process in splitting step 2. Would come down to:

1. Create the _prerelease_. Triggers pipelines with the event `release` and type `prerelease`.
2. Edit the _prerelease_ by uploading the signed artifact and removing the unsigned artifact. Triggers pipelines with event `release` and type `edited`.
3. Edit the _prerelease_ again and remove the _prerelease_ option. Triggers pipelines with event `release` and type `released`.

I will keep the issue open for now to verify the process with the next release.

**Comment by mmerklinger** [comment]
The latest version `2.3.3` is available on PyPI again.

**Comment by brevilo** [comment]
Confirmed. Thanks!
