### ISSUE TITLE
.ui to .py file conversion problem

### ISSUE THREAD

**Issue by daringer** [Nitrokey/nitrokey-app2#63]
Currently the `.py` files are not part of the repository and must be generated after checkout using `make build-ui`, this approach was chosen to avoid checking in generated files.

This approach introduces the drawback that an additional step is needed to run the app. Best case we find a way to use the `.ui` files directly within python so no additional (`make`) step is needed ...

**Comment by bordenc** [comment]
[Is this what you're looking for?](https://doc.qt.io/qt-5/quiloader.html)

**Comment by mmerklinger** [comment]
Just a remark for changing this. The *pyinstaller* we use for building the binaries doesn't detect dynamically loaded `*.ui` files during build. Means it will still succeed to build a binary but then crash during runtime, because the `*.ui` files aren't part of it. We would need to change the configuration for *pyinstaller* to include the files. This was also initially the reason why I suggested to change it, because I found to be cleaner.
